### ISSUE TITLE
ie8 coat of arms and logo are missing

### ISSUE THREAD

**Issue by TrebBrennan** [govau/GOLD#14]
![screen shot 2018-02-22 at 2 55 32 pm](https://user-images.githubusercontent.com/15899197/36519631-bf1e81aa-17e0-11e8-9bc2-c5a1e7ad6eea.png)

**Comment by elisechant** [comment]
meh

**Comment by elisechant** [comment]
time to move on Australia, no one cares about ie8 anymore

**Comment by TrebBrennan** [comment]
Hi @elisechant, thanks for your feedback. Our team are working hard to support as many users as possible.

**Comment by alex-page** [comment]
This is fixed
