### ISSUE TITLE
ie8 button hover is incorrect. 

### ISSUE THREAD

**Issue by TrebBrennan** [govau/GOLD#16]
Possibly also an issue in UIKit?

![screen shot 2018-02-22 at 2 59 16 pm](https://user-images.githubusercontent.com/15899197/36520598-f17d9384-17e5-11e8-9041-c0ed96f98e05.png)

**Comment by alex-page** [comment]
Related: https://github.com/govau/uikit/issues/312

**Comment by alex-page** [comment]
This is an issue in [govau/uikit](https://github.com/govau/uikit) and has been added as an issue.
