### ISSUE TITLE
ie8 examples are missing

### ISSUE THREAD

**Issue by TrebBrennan** [govau/GOLD#20]
![screen shot 2018-02-22 at 4 17 49 pm](https://user-images.githubusercontent.com/15899197/36521654-ffba257e-17eb-11e8-8e76-1c241341f0a7.png)

**Comment by alex-page** [comment]
This seems to be a non issue. 

I tested this and after some patience the iframe loads in. Seems like IE is struggling a little bit but then it works. Can't really blame IE8 for that 😬
