### ISSUE TITLE
ie9 accordion chevron is in the incorrect position when closed

### ISSUE THREAD

**Issue by TrebBrennan** [govau/GOLD#22]
Expected
![screen shot 2018-02-22 at 4 28 25 pm](https://user-images.githubusercontent.com/15899197/36521881-752466b6-17ed-11e8-874e-4ef1e43093c8.png)

Result
![screen shot 2018-02-22 at 4 29 13 pm](https://user-images.githubusercontent.com/15899197/36521902-8f0cadb8-17ed-11e8-95c8-cf31c9806c5d.png)

**Comment by alex-page** [comment]
Wow what a doozey. This was due to GOLD not having browser requirements so autoprefixer was going loco!
