### ISSUE TITLE
Safari: Component search-box styling

### ISSUE THREAD

**Issue by TrebBrennan** [govau/GOLD#3]
Expected.
![screen shot 2018-02-22 at 11 56 28 am](https://user-images.githubusercontent.com/15899197/36514192-7308e3f0-17c7-11e8-9a66-0cac7a443c49.png)

Result.
![screen shot 2018-02-22 at 11 54 54 am](https://user-images.githubusercontent.com/15899197/36514205-7b864568-17c7-11e8-8ada-fc387445a160.png)
(Screenshot: iOS v8, Safari)

**Comment by alex-page** [comment]
This should be fixed with https://github.com/govau/GOLD/commit/52cf66b946200a6a6d5519deffb13ff7788b49d0

@TrebBrennan can you please QA
