### ISSUE TITLE
'Header' component incorrectly mentions 'crest' instead of 'Commonwealth Coat of Arms'

### ISSUE THREAD

**Issue by gordongrace** [govau/GOLD#30]
https://gold.service.gov.au/components/header/

Currently:

> The header at the top of the page. Usually contains an Australian Government Crest, logo and navigation.

Expected:

>The header at the top of the page. Usually contains a Commonwealth Coat of Arms,  branding and navigation.

Refer:
Style manual, 6th ed. p294:

> The arms are sometimes incorrectly referred to as the ‘crest’. In the language of heraldry, a crest is ‘a device above the shield and helmet of a coat of arms’. In the Commonwealth Coat of Arms, the crest is the wreath and the seven-pointed Commonwealth Star.

**Comment by alex-page** [comment]
Thanks @gordongrace want to have a go doing a PR it's really easy 😄?
https://github.com/govau/GOLD/edit/develop/content/components/header/default.md

Otherwise i'll fix this up on Monday.

**Comment by TrebBrennan** [comment]
Fixed [here](https://github.com/govau/GOLD/commit/8bcae16de224b2113077ca942fab2ca5bc43e90f), just waiting for deployment.

Thanks @gordongrace
