### ISSUE TITLE
Safari: Released component card, icon size

### ISSUE THREAD

**Issue by TrebBrennan** [govau/GOLD#4]
Expected
![screen shot 2018-02-22 at 11 59 42 am](https://user-images.githubusercontent.com/15899197/36514304-f33fb9cc-17c7-11e8-9cc3-504f206be9e0.png)

Result
![screen shot 2018-02-22 at 11 59 25 am](https://user-images.githubusercontent.com/15899197/36514314-fb287cbe-17c7-11e8-96b6-0dd42b370a98.png)
(Screenshot: iOS v8, Safari)

**Comment by alex-page** [comment]
This should be resolved with https://github.com/govau/GOLD/commit/29f8dd869efe9a2bfa60f76000646d38bbb5356f
