### ISSUE TITLE
Safari: Released components card list, missing components

### ISSUE THREAD

**Issue by TrebBrennan** [govau/GOLD#5]
Expected.
All 24 components live/released.

Result.
Only 2 components.
![screen shot 2018-02-22 at 11 59 25 am](https://user-images.githubusercontent.com/15899197/36514424-7ecf6348-17c8-11e8-9fd9-7c2b19bcc019.png)
(Screenshot: iOS v8, Safari)

**Comment by alex-page** [comment]
This should be resolved with https://github.com/govau/GOLD/commit/29f8dd869efe9a2bfa60f76000646d38bbb5356f
