### ISSUE TITLE
Safari: Download page, responsive layout issues.

### ISSUE THREAD

**Issue by TrebBrennan** [govau/GOLD#7]
**Expected.**
Consistent layouts.
- 'Documentation link' not to overlap with 'component name'
- 'Dependencies' to align with 'component name'
![screen shot 2018-02-22 at 12 31 36 pm](https://user-images.githubusercontent.com/15899197/36515483-bfe99ca4-17cd-11e8-875b-c364f71f8d47.png)

**Result.**
![screen shot 2018-02-22 at 12 27 31 pm](https://user-images.githubusercontent.com/15899197/36515459-a29d1d60-17cd-11e8-81fc-e2e5f540aed4.png)
(Screenshot: iOS v8, Safari)

**Comment by alex-page** [comment]
Can't replicate
