### ISSUE TITLE
Download page, 'Your build' title missing margin-top

### ISSUE THREAD

**Issue by TrebBrennan** [govau/GOLD#8]
**Expected**
About `3unit` between the components and "Your build" heading.

**Result**
No space.
![screen shot 2018-02-22 at 12 44 18 pm](https://user-images.githubusercontent.com/15899197/36515732-ecc4cbc6-17ce-11e8-8edd-9f0eb2059aa6.png)
(See in multiple browsers)

**Comment by alex-page** [comment]
Fixed this one
